spring:
  application:
    name: notification-service
  ## sending mails using java mail sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: pedalplanetbicycles@gmail.com
    password: lwuouxyjayzvvkcn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory

  ## kafka configuration only bootstrap server taking from here all others are configurable
  kafka:
    consumer:
      bootstrap-servers: localhost:9092


server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

## zipkin configuration
  zipkin:
    baseUrl: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0


