server:
  port: 8082
spring:
  application:
    name: question-service
  datasource:
    url: jdbc:postgresql://localhost:5432/quizApp
    username: postgres
    password: password#2#2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  ## zipkin configuration

  zipkin:
    baseUrl: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0

