spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizDb
    username: postgres
    password: password#2#2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: quiz-service

server:
  port: 8081

##circuit breaker

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      quizService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      quizService:
        maxRetryAttempts: 3
        waitDuration: 5s
  timelimiter:
    instances:
      quizService:
        timeoutDuration: 3s

  ## zipkin configuration

  zipkin:
    baseUrl: http://localhost:9411

  tracing:
    sampling:
      probability: 1.0

#kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      defaultTopic: "notificationTopic"

    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
